import { useChatStore } from '../../stores/chatStore'
import { ExternalLink, Star, ShoppingCart } from 'lucide-react'

export default function ProductSuggestions() {
  const { messages } = useChatStore()

  // Get the latest message with product suggestions
  const latestMessageWithProducts = messages
    .filter(m => m.productSuggestions?.length > 0)
    .pop()

  if (!latestMessageWithProducts?.productSuggestions?.length) {
    return null
  }

  const products = latestMessageWithProducts.productSuggestions

  return (
    <div className="bg-white border-t border-gray-200 px-6 py-4">
      <h3 className="text-lg font-semibold text-gray-900 mb-4">
        Recommended Products
      </h3>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {products.map((product, index) => (
          <div
            key={index}
            className="border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow"
          >
            {/* Product Image */}
            <div className="aspect-square bg-gray-100 rounded-lg mb-3 overflow-hidden">
              {product.image_url ? (
                <img
                  src={product.image_url}
                  alt={product.title}
                  className="w-full h-full object-cover"
                />
              ) : (
                <div className="w-full h-full flex items-center justify-center text-gray-400">
                  <ShoppingCart size={32} />
                </div>
              )}
            </div>

            {/* Product Info */}
            <div className="space-y-2">
              <h4 className="font-medium text-gray-900 line-clamp-2">
                {product.title || 'Product Title'}
              </h4>
              
              <div className="flex items-center justify-between">
                <span className="text-lg font-bold text-primary-600">
                  ${product.price || '0.00'}
                </span>
                
                {product.rating && (
                  <div className="flex items-center gap-1">
                    <Star size={14} className="text-yellow-400 fill-current" />
                    <span className="text-sm text-gray-600">
                      {product.rating}
                    </span>
                  </div>
                )}
              </div>

              {/* Product Description */}
              {product.description && (
                <p className="text-sm text-gray-600 line-clamp-2">
                  {product.description}
                </p>
              )}

              {/* Action Buttons */}
              <div className="flex gap-2 pt-2">
                <a
                  href={product.url || '#'}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex-1 flex items-center justify-center gap-1 px-3 py-2 bg-primary-600 text-white text-sm rounded-lg hover:bg-primary-700 transition-colors"
                >
                  <ExternalLink size={14} />
                  View Product
                </a>
                
                <button className="px-3 py-2 border border-gray-300 text-sm rounded-lg hover:bg-gray-50 transition-colors">
                  Save
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Disclaimer */}
      <p className="text-xs text-gray-500 mt-4 text-center">
        Product recommendations are generated by AI. Prices and availability may vary.
      </p>
    </div>
  )
}
